spring:
  profiles:
    active: dev


---
# 8004端口配置，就餐服务
server:
  port: 8004
#spring的配置
spring:
  profiles: dev
  application:
    name: smartmem-dining-service-povider-8004
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dining_service
    username: postgres
    password: postgres

mybatis-plus:
  configuration:
    # 配置下划线转换为驼峰命名法
    map-underscore-to-camel-case: true
    # 日志打印查询sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 将数据库中为null的字段也取出
    call-setters-on-nulls: true

  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.cisdi.smartmem.pojo

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


---
# 8005端口配置，理发服务
server:
  port: 8005
#spring的配置
spring:
  profiles: dev
  application:
    name: smartmem-dining-service-povider-8004 #这改一下
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dining_service #这改一下
    username: postgres
    password: postgres

mybatis-plus:
  configuration:
    # 配置下划线转换为驼峰命名法
    map-underscore-to-camel-case: true
    # 日志打印查询sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 将数据库中为null的字段也取出
    call-setters-on-nulls: true

  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.cisdi.smartmem.pojo

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/



